### ISSUE TITLE
serveStatic not working

### ISSUE THREAD

**Issue by goodpixels** [basicallydan/interfake#39]
so here's my code, taken straight from the documentation:

```
var Interfake	= require( 'interfake' );
var interfake	= new Interfake();
var filePath	= path.join(__dirname, './');

interfake.serveStatic( '/static', filePath );
interfake.listen( 3000 );
```
but it doesn't work as expected. whenever i try to access `index.html` in the browser (`http://localhost:3000/static/index.html`), nothing happens.

here's my directory structure:

```
test.js
index.html
```

and here's how i'm running it:

`node test.js`

i also tried running the web page example (`fluent-web-page-test.js`), but after installing all dependencies it still won't work.

here's the output from the terminal:

```
ChickenMaster:interfake john$ node examples-javascript/fluent-web-page-test.js

/Users/john/Sites/interfake/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:238
var nonInheritedTags = new Set([
                           ^
ReferenceError: Set is not defined
    at Object.<anonymous> (/Users/john/Sites/interfake/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:238:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/john/Sites/interfake/node_modules/zombie/node_modules/jsdom/lib/jsdom/living/index.js:8:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/john/Sites/interfake/node_modules/zombie/lib/dom/index.js:5:11)
    at Module._compile (module.js:456:26)
ChickenMaster:interfake john$ 
```

am i doing something wrong or is this a bug?

**Comment by basicallydan** [comment]
Hey John

Certain that the web page example is a bug with a dependency (Zombie - it doesn't really work, so I removed it), and the first one is probably a bug too. I've just tried your code and it doesn't work.

Really sorry about this. I'll have a look within the next few days but at the moment I'm on a holiday so I can't guarantee it'll be a particularly quick fix.

**Comment by goodpixels** [comment]
no worries man, enjoy your holiday while you still can :+1:

**Comment by basicallydan** [comment]
Hey @goodpixels, looking at this now! Two more people on the [gitter channel](https://gitter.im/basicallydan/interfake) have reported problems. Hopefully it won't take long!

**Comment by basicallydan** [comment]
Hope this is all good, @goodpixels. I added a unit test for it and tested it manually. Sorry about the inconvenience! Go ahead and update to 1.14.0 :)

**Comment by goodpixels** [comment]
Fantastic! All is good now, many thanks for fixing this so quickly!

**Comment by basicallydan** [comment]
Hooray!
